version: '3.8'

services:
  webrcm:
    build: .
    ports:
      - "3000:3000"
    container_name: webrcm-app
    environment:
      - NODE_ENV=production
    # Uncomment to rebuild without cache
    # build:
    #   context: .
    #   no_cache: true
